language: node_js
sudo: false

node_js:
  - node

before_script:
  - npm cache clean
  - npm install -g node-sass
  - npm install -g mkdirp
  - npm install -g true-case-path
  - npm install

env:
  global:
    - export NODE_ENV=test
